all: hw05_functions.o
		gcc hw0501.c hw05_functions.o -o hw0501
		gcc hw0502.c hw05_functions.o -o hw0502
		gcc hw0503.c hw05_functions.o -o hw0503
		gcc hw0504.c hw05_functions.o -o hw0504

hw05_function.o:hw05_functions.c
		gcc -c hw05_functions.c -o hw05_functions.o

clean:
		rm -rf hw0501
		rm -rf hw0502
		rm -rf hw0503
		rm -rf hw0504
