all:
			gcc hw301.c -o hw0301
			gcc hw302.c -o hw0302
			gcc hw303.c -o hw0303
			gcc hw304.c -o hw0304
			gcc hw305.c -o hw0305

clean:
			rm -rf hw0301
			rm -rf hw0302
			rm -rf hw0303
			rm -rf hw0304
			rm -rf hw0305
